service: LiveChat
frameworkVersion: '3'

plugins:
  - serverless-api-gateway-throttling

provider:
  name: aws
  runtime: nodejs16.x
  environment: ${file(env.json)}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}

functions:
  - ${file(src/serverless-resources/functions.yml)}
